### ISSUE TITLE
ion-calendar is not know element

### ISSUE THREAD

**Issue by marticrespi** [gnucoop/ionic2-extra#1]
Hi, I have installed in my project, but when I try to use shows me an error.

    <ion-header>
      <ion-navbar>
        <button ion-button menuToggle>
          <ion-icon name="menu"></ion-icon>
        </button>
        <ion-title>About</ion-title>
        <ion-buttons end>
          <button ion-button icon-only (click)="presentPopover($event)">
            <ion-icon name="more"></ion-icon>
          </button>
        </ion-buttons>
      </ion-navbar>
    </ion-header>
    <ion-content>
        <ion-calendar (change)="onPeriodChange($event)"></ion-calendar>
    </ion-content>

Here is the error:

    polyfills.js:3 Unhandled Promise rejection: Template parse errors:
    'ion-calendar' is not a known element:
    1. If 'ion-calendar' is an Angular component, then verify that it is part of this module.
    2. If 'ion-calendar' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
    [ERROR ->]<ion-calendar (change)="onPeriodChange($event)"></ion-calendar>

Thanks for your work, but can you provide more information about how use it properly?

**Comment by codeartisanorg** [comment]
I was able to get this working, by adding this to app.module.ts

```
import { NgModule, ErrorHandler, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { ION_CALENDAR_DIRECTIVES, IonCalendar } from '@ionic2-extra/calendar';
```

and then after providers in `@NgModule` I added

`schemas: [CUSTOM_ELEMENTS_SCHEMA]`

in my calendar.ts file I added

`import { ION_CALENDAR_DIRECTIVES, IonCalendar } from '@ionic2-extra/calendar';`

Edit: You also need `IonCalendar` inside `declarations` as well

**Comment by trik** [comment]
@marticrespi Sorry for the lack of documentation.. we'll publish the readme ASAP

**Comment by trik** [comment]
refers #3

**Comment by guimap** [comment]
i already added code inside of my module
```
...
import { IonCalendarModule } from '@ionic2-extra/calendar';
...
```
```
@NgModule({
  ...
  imports: [
    IonCalendarModule,
    ...
  ],
  declaractions: [
    MyComponentUsingCalendar
  ]
})
```
and inside of my page i added
```
import {IonCalendar, ION_CALENDAR_DIRECTIVES, IonCalendarEntry, IonCalendarChange} from  '@ionic2-extra/calendar';
```
and iside of my template page
```
<ion-calendar (change)="onPeriodChange($event)"></ion-calendar>
```
but when run, nothing appear inside of the tag, it's empty :(
anyone did this work ?

**Comment by trik** [comment]
@GuimaP see this example
https://plnkr.co/edit/hzBlVNYp9vEta5ljyFCD
