### ISSUE TITLE
ion-calendar doesnt show

### ISSUE THREAD

**Issue by guimap** [gnucoop/ionic2-extra#3]
I'm trying to use the ion calendar.
i've added import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular'; into module.ts

and inside of my page i added 
import { ION_CALENDAR_DIRECTIVES, IonCalendar } from '@ionic2-extra/calendar';

and inside of my template:
<ion-calendar (change)="onPeriodChange($event)"></ion-calendar>

but the calendar doesn't show

**Comment by trik** [comment]
you have to import IonCalendarModule from in your module

```typescript
...
import { IonCalendarModule } from '@ionic2-extra/calendar';
...


@NgModule({
  ...
  imports: [
    IonCalendarModule,
    ...
  ],
  declaractions: [
    MyComponentUsingCalendar
  ]
})
```

**Comment by guimap** [comment]
i already added code inside of my module
```
...
import { IonCalendarModule } from '@ionic2-extra/calendar';
...


@NgModule({
  ...
  imports: [
    IonCalendarModule,
    ...
  ],
  declaractions: [
    MyComponentUsingCalendar
  ]
})
```

and inside of my page i added 

```
import {IonCalendar, ION_CALENDAR_DIRECTIVES, IonCalendarEntry, IonCalendarChange} from  '@ionic2-extra/calendar';
```

and iside of my template page 
```
<ion-calendar (change)="onPeriodChange($event)"></ion-calendar>
``` 

but when run, nothing appear inside of the tag, it's empty :(
